package com.example.perpustakaan.database

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.perpustakaan.enums.AuthorStatus
import com.example.perpustakaan.enums.BookType
import com.example.perpustakaan.enums.Language
import com.example.perpustakaan.enums.Priority
import com.example.perpustakaan.enums.UserStatus

@Entity
data class Series(

    @PrimaryKey(autoGenerate = true)
    val uid: Int = 0, // Setting to 0 is treated as unset by the DB and therefore autogenerated

    // Series info
    val primaryLanguage: Language  = Language.ENGLISH,
    val titleEn: String            = "",
    val titleJp: String            = "",
    val description: String        = "",
    val bookType: BookType         = BookType.MANGA,
    val authorStatus: AuthorStatus = AuthorStatus.IN_PRODUCTION,
    val totalVolumes: String       = "",

    // User info
    val isOnWishlist: Boolean      = false,
    val userStatus: UserStatus     = UserStatus.READING,
    val volumesOwned: String       = "1",
    val priority: Priority         = Priority.NIL,
    val rating: Int                = 0,
    val notes: String              = ""

) {

    /**
     * Returns the correct title depending on the primaryLanguage field.
     */
    fun primaryTitle(): String {
        return if (primaryLanguage == Language.ENGLISH) titleEn else titleJp
    }

    /**
     * Converts the extended Series object to a DisplaySeries.
     */
    fun toDisplaySeries(): DisplaySeries {
        return DisplaySeries(
            uid          = uid,
            title        = primaryTitle(),
            bookType     = bookType,
            isOnWishlist = isOnWishlist,
            userStatus   = userStatus,
            volumesOwned = volumesOwned
        )
    }

}
